# Generated by Django 4.1.7 on 2023-04-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0003_alter_order_order_id_in_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id_in_shop',
            field=models.IntegerField(unique=True, verbose_name='Order id in shop'),
        ),
    ]
